class-32/demo/ViewComponentsDemo/ViewComponentsDemo/Models/ErrorViewModel.cs
namespace ViewComponentsDemo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

class-32/demo/ViewComponentsDemo/ViewComponentsDemo/Components/LoggedInUserViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace ViewComponentsDemo.Components
{
    public class LoggedInUserViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            string username
              = HttpContext.Request.Cookies["username"] != null ?
              HttpContext.Request.Cookies["username"] : String.Empty;

            ViewModel user = new ViewModel()
            {
                Username = username
            };

            return View(user);
        }

        public class ViewModel
        {
            public string Username { get; set; }
        }
    }
}

class-32/demo/ViewComponentsDemo/ViewComponentsDemo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ViewComponentsDemo.Models;

namespace ViewComponentsDemo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

class-32/demo/ViewComponentsDemo/ViewComponentsDemo/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ViewComponentsDemo.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

class-32/demo/ViewComponentsDemo/ViewComponentsDemo/Pages/Settings/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ViewComponentsDemo.Pages.Settings
{
    public class IndexModel : PageModel
    {
        [BindProperty]
        public SettingsVM Settings { get; set; }
        public void OnGet()
        {
            string username 
                = HttpContext.Request.Cookies["username"] != null ? 
                HttpContext.Request.Cookies["username"] : String.Empty;

            Settings = new SettingsVM()
            {
                Name = username
            };
        }

        public void OnPost() 
        { 
            // Cookies We can use it fto track or remember
            // user prefernces and store authentcate token 

            CookieOptions cookieOptions = new CookieOptions();
            cookieOptions.Expires = DateTime.UtcNow.AddDays(7);

            HttpContext.Response.Cookies.Append("username", Settings.Name, cookieOptions);  

        }

        public class SettingsVM
        {
            public string Name { get; set; }    
        }
    }
}

class-32/demo/ViewComponentsDemo/ViewComponentsDemo/Pages/Shared/Components/LoggedInUser/Default.cshtml
@model ViewComponentsDemo.Components.LoggedInUserViewComponent.ViewModel

@if(Model.Username != null){
    <span class="navbar-text">Weclome back, @Model.Username</span>
}

class-32/demo/ViewComponentsDemo/ViewComponentsDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ViewComponentsDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ViewComponentsDemo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ViewComponentsDemo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            @await Component.InvokeAsync("LoggedInUser")
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ViewComponentsDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>